apiVersion: v1
kind: Secret
metadata:
  name: ruihuawebsite-app-secret
  namespace: default
type: Opaque
stringData:
  # Admin bootstrap account
  ADMIN_USERNAME: ""
  ADMIN_PASSWORD: ""

  # DingTalk robot config
  DINGTALK_WEBHOOK_URL: ""
  DINGTALK_SECRET: ""

  # SMS account config
  SMS_USERNAME: "rrxt"
  SMS_PASSWORD: "Renrui123"

  # Auth config
  JWT_SECRET: ""
