apiVersion: v1
kind: ConfigMap
metadata:
  name: ruihua-cms-config
  namespace: default
data:
  # 数据库配置
  DB_HOST: "mongodb-service"
  DB_PORT: "27017"
  DB_NAME: "ruihua_cms"
  MONGODB_URL: "mongodb://mongodb-service:27017/ruihua_cms"
  
  # 应用配置
  NODE_ENV: "production"
  PORT: "3000"
  
  # 管理员账号配置
  ADMIN_USERNAME: "zhice"
  ADMIN_PASSWORD: "zhiceruihua123"
  
  # 钉钉通知配置
  #DINGTALK_WEBHOOK_URL: "https://oapi.dingtalk.com/robot/send?access_token=YOUR_ACCESS_TOKEN"
  DINGTALK_WEBHOOK_URL: "https://oapi.dingtalk.com/robot/send?access_token=862cc9da41b5779bbdb9d3c967e9da553ae0ea59e45f9e67cf3e3dd0af48e77f"
  DINGTALK_SECRET: "SECed8d93cf0a8a5fb61938069393315e4074109958ea40da68657a913b21d9d5f9"