apiVersion: v1
kind: ConfigMap
metadata:
  name: ruihua-cms-config
  namespace: default
data:
  # 数据库配置
  DB_HOST: "mongodb-service"
  DB_PORT: "27017"
  DB_NAME: "ruihua_cms"
  MONGODB_URL: "mongodb://mongodb-service:27017/ruihua_cms"
  
  # 应用配置
  NODE_ENV: "production"
  PORT: "3000"
  
  # 管理员账号配置
  ADMIN_USERNAME: "zhice"
  ADMIN_PASSWORD: "zhiceruihua123"