apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- app-secret.yaml
- tos-secret.yaml
- mongodb-deployment.yaml
- app-deployment.yaml

images:
- name: ruihuawebsite
  newTag: v1.0.0

commonLabels:
  project: ruihuawebsite
  version: v1.0

namespace: default
